### ISSUE TITLE
Rinkeby APM DAO can't be inspected

### ISSUE THREAD

**Issue by sembrestels** [aragon/aragon-cli#1082] opened 2019-12-17 16:27 UTC
## 🐛 Bug Report

Error when inspecting APM DAOs from the CLI. It causes #554 again.

### Have you read the [Contributing Guidelines on issues](https://github.com/aragon/aragon-cli/blob/master/CONTRIBUTING.md#ways-to-contribute)?

Yes

#### Mainnet or testnet?

Rinkeby (in Mainnet works with the its own APM regitry: 0xa1213ff38A8a450f47D4d6a737924A0e3Af3603a)

#### Organization

AragonPM (0x2DF31C5fcBB94656fc98e2953cF0DA03e2885Cfa)

#### Environment

- OS and OS version: Ubuntu 19.04
- Node version: 10.17.0

## To Reproduce

```
npx aragon dao apps 0x2DF31C5fcBB94656fc98e2953cF0DA03e2885Cfa --environment rinkeby --debug
```

## Expected behavior

Show a list of DAO apps

## Actual Behavior

```
❯ aragonCLI version: 6.4.1
❯ argv: ["/usr/local/bin/node","/home/sem/Projects/committees/node_modules/.bin/aragon","dao","apps","0x2DF31C5fcBB94656fc98e2953cF0DA03e2885Cfa","--environment","rinkeby","--debug"]
Inspecting DAO [started]
→ Fetching apps for 0x2DF31C5fcBB94656fc98e2953cF0DA03e2885Cfa...
Redefining LocalForage driver: memoryStorageDriver
✖ Error inspecting DAO apps
❯ Error: CONNECTION ERROR: Couldn't connect to node on WS.
    at Object.InvalidConnection (/home/sem/Projects/committees/node_modules/@aragon/cli/node_modules/web3-core-helpers/src/errors.js:35:16)
    at WebsocketProvider._timeout (/home/sem/Projects/committees/node_modules/@aragon/cli/node_modules/web3-providers-ws/src/index.js:255:48)
    at W3CWebSocket.connection.onclose (/home/sem/Projects/committees/node_modules/@aragon/cli/node_modules/web3-providers-ws/src/index.js:155:15)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/home/sem/Projects/committees/node_modules/@aragon/cli/node_modules/yaeti/lib/EventTarget.js:107:17)
    at W3CWebSocket.onClose (/home/sem/Projects/committees/node_modules/@aragon/cli/node_modules/web3-providers-ws/node_modules/websocket/lib/W3CWebSocket.js:228:10)
    at WebSocketConnection.<anonymous> (/home/sem/Projects/committees/node_modules/@aragon/cli/node_modules/web3-providers-ws/node_modules/websocket/lib/W3CWebSocket.js:201:17)
    at WebSocketConnection.emit (events.js:198:13)
    at WebSocketConnection.drop (/home/sem/Projects/committees/node_modules/@aragon/cli/node_modules/web3-providers-ws/node_modules/websocket/lib/WebSocketConnection.js:475:14)
    at /home/sem/Projects/committees/node_modules/@aragon/cli/node_modules/web3-providers-ws/node_modules/websocket/lib/WebSocketConnection.js:303:18
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

## Reproducible Demo

I asked a friend with another computer and another internet connection, and the problem persists.

**Comment by 0xGabi** [comment] 2020-01-23 17:42
As far as I debugg this issue is related with the `@aragon/wrapper` not recognizing the APM DAO

**Comment by 0x6431346e** [comment] 2020-02-10 17:33
> We look at it a couple of weeks ago and it seems there is an issue with how aragon.js handle apm dao. Like the address is not detected as a dao. And somehow releated to the Proxy object that aragon.js creates. - @0xGabi 

> Btw I spent sometime debbuging the APM DAO issue (aragon-cli/#1082) and I think there is two things happening:
> 1. The APM DAO deployed on aragen is not recognized as a dao, I think there is some bug during deployment
> 2. We are not handleing @aragon/wrapper observers correctly on the aragonCLI - @0xGabi

**Comment by litvintech** [comment] 2020-03-25 14:14
@0xGabi @sohkai I have the same issue right now. Publishing process to APM in Rinkeby seems broken

**Comment by steffclearteam** [comment] 2021-02-24 19:17
This bug is reproducible

**Comment by eliobricenov** [comment] 2021-03-02 17:17
I'm getting a slightly different output but I suspect it is related to the same issue.

```web3-shh package will be deprecated in version 1.3.5 and will no longer be supported.
web3-bzz package will be deprecated in version 1.3.5 and will no longer be supported.
Inspecting DAO [started]
→ Fetching apps for 0xDa89ac3fe0327D2304E1A61fD334D38acD3559B5...
Inspecting DAO [failed]
→ Network: incorrect value provided.
✖ Error: Network: incorrect value provided.
    at Object.toNetwork (/home/elio/.nvm/versions/node/v12.21.0/lib/node_modules/@aragon/cli/node_modules/@aragon/connect-core/src/utils/network.ts:71:11)
    at new ConnectorTheGraph (/home/elio/.nvm/versions/node/v12.21.0/lib/node_modules/@aragon/cli/node_modules/@aragon/connect-thegraph/src/connector.ts:74:20)
    at getConnector (/home/elio/.nvm/versions/node/v12.21.0/lib/node_modules/@aragon/cli/node_modules/@aragon/connect/src/connect.ts:56:12)
    at connect (/home/elio/.nvm/versions/node/v12.21.0/lib/node_modules/@aragon/cli/node_modules/@aragon/connect/src/connect.ts:95:5)
    at getAppsFromAragonConnect (/home/elio/.nvm/versions/node/v12.21.0/lib/node_modules/@aragon/cli/src/commands/dao_cmds/apps.js:95:21)
    at Task.getAppsFromAragonConnect [as task] (/home/elio/.nvm/versions/node/v12.21.0/lib/node_modules/@aragon/cli/src/commands/dao_cmds/apps.js:137:21)
```

**Comment by eliobricenov** [comment] 2021-03-03 14:58
> As far as I debugg this issue is related with the `@aragon/wrapper` not recognizing the APM DAO

Hi @0xGabi, would you mind pointing out which files are related to the issues? I'm trying to save some time on debugging,

**Comment by nivida** [comment] 2021-03-17 09:43
Our engineer @nestorbe was investigating this bug and it wasn't reproducible. Because of this will I close this bug report. Feel free to open a new issue and to mention us in the bug report description in case you still encounter this problem.

**Closed by nivida** 2021-03-17 09:43 UTC
Labels: 🐛 bug, 📟 cli

**Comment by anthonymartin** [comment] 2021-10-24 22:53
@nivida I can reproduce this error. same issue:

```
❯ aragonCLI version: 7.1.6
❯ argv: ["/Users/anthonymartin/.nvm/versions/node/v12.22.1/bin/node","/usr/local/bin/aragon","dao","apps","REDACTED","--env","aragon:mainnet","--ws-rpc","wss://mainnet.infura.io/v3/REDACTED","--debug"]
❯ Could not find 'arapp.json'. Using the default configuration
Inspecting DAO [started]
→ Fetching apps for 0xREDACTED...
Inspecting DAO [failed]
→ Network: incorrect value provided.
✖ Error: Network: incorrect value provided.
    at Object.toNetwork (/usr/local/lib/node_modules/@aragon/cli/node_modules/@aragon/connect-core/src/utils/network.ts:71:11)
    at new ConnectorTheGraph (/usr/local/lib/node_modules/@aragon/cli/node_modules/@aragon/connect-thegraph/src/connector.ts:74:20)
    at getConnector (/usr/local/lib/node_modules/@aragon/cli/node_modules/@aragon/connect/src/connect.ts:56:12)
    at connect (/usr/local/lib/node_modules/@aragon/cli/node_modules/@aragon/connect/src/connect.ts:95:5)
    at getAppsFromAragonConnect (/usr/local/lib/node_modules/@aragon/cli/src/commands/dao_cmds/apps.js:95:21)
    at Task.getAppsFromAragonConnect [as task] (/usr/local/lib/node_modules/@aragon/cli/src/commands/dao_cmds/apps.js:137:21)
```
    
it's the same for rinkeby and mainnet

**Comment by anthonymartin** [comment] 2021-10-24 22:57
ah, here's the fix - found elsewhere on the internet: 

> Basically the aragonCLI is completely useless unless it's running inside an aragon project. Installing it as a global tool 
does not work as it looks for arapp.json and naturally is unable to find it. Where it actually looks for it im not sure. ill have to investigate further. I am going to open a git issue for this.
> Basically the workaround. Is to deploy the tutorial aragon project and run your CLI override commands from there.
