### ISSUE TITLE
Cannot `aragon start` when `devchain` is running

### ISSUE THREAD

**Issue by vporton** [aragon/aragon-cli#1121] opened 2019-12-21 19:01 UTC
## 🐛 Bug Report

Accordingly https://hack.aragon.org/docs/cli-main-commands `aragon run` "checks whether IPFS and a local Ethereum development chain (devchain) are running and if not it will start them".

But if I run in three terminals:

```sh
npx aragon devchain
npx aragon ipfs
npx aragon run
```

I get:
```
    ✖ Check devchain status
      → Process with ID 467811 already running at port 8545
```

Must not refrain to start if `devchain` is already running.

### Have you read the [Contributing Guidelines on issues](https://github.com/aragon/aragon-cli/blob/master/CONTRIBUTING.md#ways-to-contribute)?

Yes.

#### Mainnet or testnet?

RPC.

#### Environment

- OS and OS version: Ubuntu 19.10

**Comment by macor161** [comment] 2019-12-23 01:06
I can't reproduce this bug neither on Mac or Ubuntu. Can you share your logs?

**Comment by ajsantander** [comment] 2020-01-31 13:00
Closing this issue because aragon start will be deprecated soon and replaced by the buidler-aragon plugin.

**Closed by ajsantander** 2020-01-31 13:00 UTC
Labels: 🐛 bug
