### ISSUE TITLE
dao acl create: Cannot read property 'description' of undefined

### ISSUE THREAD

**Issue by svetlanama** [aragon/aragon-cli#497] opened 2019-06-04 13:36 UTC
## 🐛 Bug Report

Update transaction path description to new format. Related to https://github.com/aragon/forum/issues/2
## Context

Hi,

I'm following this [instruction](https://forum.aragon.org/t/guide-custom-aragon-organization-deployment-using-the-cli/507) 
and noticed that commands related to assigning grants  
like ```dao acl create ....```
give me an error ```Cannot read property 'description' of undefined```

The error behavior is unpredictable (sometimes it requires a delay before calling it, sometimes it does not help)
The thing that I can not achieve the end of instruction the final result (since there are a few commands and one of them every time fails, which makes me start everything from the beginning).

Wonder if there is some way to control this step.
Thanks.

**Comment by 0x6431346e** [comment] 2019-06-05 10:35
> The thing that I can not achieve the end of instruction the final result (since there are a few commands and one of them every time fails, which makes me start everything from the beginning).

Hey @svetlanama , can you expand on this please? (it shouldn't make you start over again)

Which step is this?
Does this happen locally, rinkeby, or mainnet?

**Comment by svetlanama** [comment] 2019-06-05 11:11
Hi @0x6431346e 
1. it shouldn't make you start over again: 
after getting an error
```
Cannot read property 'description' of undefined
```
I tried to repeat and it says me
```
 ✔ Generating transaction
 ✖ Sending transaction
   → Cannot find transaction path for executing action
 ✖ Cannot find transaction path for executing action
```
so as I understand the step is broken and I need to start from the beginning. Please correct me if I'm wrong.

2. steps:
```
dao acl create [dao-address] [token-manager-address] MINT_ROLE [your-address-erc20] [your-address] --environment aragon:rinkeby
```
```
dao acl create [dao-address] [voting-app-address] CREATE_VOTES_ROLE [token-manager-address] [voting-app-address] --environment aragon:rinkeby
```
```
dao acl create [dao-address] [vault-address] TRANSFER_ROLE [finance-address] [voting-address] --environment aragon:rinkeby
```
```
dao acl create [dao-address] [finance-address] CREATE_PAYMENTS_ROLE [voting-address] [voting-address] --environment aragon:rinkeby
```
3. network: Rinkeby

4. additional
to start daemon I use: 
```aragon ipfs```


Please let me know I you need more info...

**Comment by svetlanama** [comment] 2019-06-07 09:10
Hi @0xGabi  

Does it mean that ```dao acl create``` commands work but the output is wrong only?

**Comment by 0xGabi** [comment] 2019-06-09 21:22
Hi @svetlanama for what I understand there are a couple of things going on here. Let me expand on each.

 First and most important for you to keep testing the example. To prevent:

```
✔ Generating transaction
 ✖ Sending transaction
   → Cannot find transaction path for executing action
 ✖ Cann
```
You probably need to have at least a token of `token-manager` to be able to create new votes on the `voting` app. So you need to mint yourself a token to have the necessary permissions.

Then about the  message: 

`Cannot read property 'description' of undefined` 


This issue is related with an error trying to output the transaction path to the console, nevertheless the transaction was generated and sent. So you should expect the changes to be made.

**Comment by svetlanama** [comment] 2019-06-10 20:41
@0xGabi  I see, thank you for explanations!


```
→ Cannot find transaction path for executing action
```
will keep testing this ....

**Comment by 0xGabi** [comment] 2019-06-12 07:54
Hey @svetlanama the error message: `Cannot read property 'description' of undefined` should be fixed in last release. Install it with: `npm i -g @aragon/cli`

**Comment by svetlanama** [comment] 2019-06-12 12:14
Hi @0xGabi for some reason I started to get this error 2 times in a row
step 
```dao acl create [dao-address] [token-manager-address] MINT_ROLE [your-address-erc20] [your-address] --environment aragon:rinkeby```

````
 ✖ Generating transaction
    → Cannot read property 'functions' of undefined
    Sending transaction
 ✖ Cannot read property 'functions' of undefined
```

could you re-check please, thanks!

**Comment by 0xGabi** [comment] 2019-06-17 04:09
@svetlanama I was not able to reproduce this issue. I checked with both our `stable` and `nightly` versions and is working fine. Could you further explain the steps you followed?

**Comment by svetlanama** [comment] 2019-06-18 11:43
Hi @0xGabi I made clean @aragon/cli installation and it helped, looks the was some conflicts between versions, sorry for the confusion, thank you!

**Comment by 0xGabi** [comment] 2019-06-18 14:23
Amazing! Will close the issue then.

**Closed by 0xGabi** 2019-06-18 14:23 UTC
Labels: cmd: dao acl create, 🐛 bug
