### ISSUE TITLE
dao new has hardcoded gas price

### ISSUE THREAD

**Issue by luisivan** [aragon/aragon-cli#353] opened 2019-01-22 11:43 UTC
Was creating a $10 DAO because of the hardcoded gas price, by using `dao new`. There should be a way to change gas price

**Comment by lkngtn** [comment] 2019-01-22 17:02
Related/duplicate of #346 ?

**Comment by luisivan** [comment] 2019-01-22 17:06
Seems related more than a duplicate, thanks

**Comment by 0xGabi** [comment] 2019-07-14 02:06
Superseded by #499

**Closed by 0xGabi** 2019-07-14 02:06 UTC
Labels: cmd: dao new, 🛠️ maintenance, 🦅 flock/nest high priority
