### ISSUE TITLE
Name clash with atom package manager

### ISSUE THREAD

**Issue by andriytyurnikov** [aragon/aragon-cli#131] opened 2018-06-12 06:34 UTC
Popular code editor Atom https://atom.io/ has plugin package manager `apm`
Please consider avoiding this conflict.
Popular idea - having one command with internal hierarchy like
`aragon package install`

**Comment by sohkai** [comment] 2018-06-12 11:09
Duplicate of #114.

**Closed by sohkai** 2018-06-12 11:09 UTC
