### ISSUE TITLE
aragon run --http does not install the app

### ISSUE THREAD

**Issue by 0x6431346e** [aragon/aragon-cli#273] opened 2018-11-13 15:48 UTC
To reproduce:
1. `aragon init foo`
2. `npm run start:aragon:http`
3. `npm run start:app`

Current behavior: the wrapper starts at `localhost:3000`, but the counter app is not there
![image](https://user-images.githubusercontent.com/26041347/48424817-c7859880-e763-11e8-9eb7-b0d9e4fd2f19.png)

Note: `aragon run` seems to work correctly

Any thoughts on how to debug this?

**Comment by sohkai** [comment] 2018-11-16 13:52
Hmm, does the console have any logs? Maybe it couldn't fetch the artifacts, or the local server for the app didn't spin up in time?

**Comment by 0x6431346e** [comment] 2018-11-20 16:00
Nothing uncommon, it does see only 3 apps though: kernel, acl, evm script registry.
If I run `dao apps [dao-address]` I get only the `acl` and `evmreg` :thinking: 

cli output:
```
Start a local Ethereum network [started]
Setting up a new chain from latest Aragon snapshot [started]
Setting up a new chain from latest Aragon snapshot [completed]
Starting a local chain from snapshot [started]
Local chain started at port 8545 [title changed]
Local chain started at port 8545 [completed]
Start a local Ethereum network [completed]
Check IPFS [started]
Start IPFS [started]
→ Starting IPFS at port: 5001
Start IPFS [completed]
Add local files [started]
Add local files [completed]
Check IPFS [completed]
Publish app to APM [started]
Applying version bump (major) [started]
Applying version bump (major) [completed]
Deploy contract [started]
Compile contracts [started]
Compile contracts [completed]
Deploy 'CounterApp' to network [started]
→ Deploying 'CounterApp' to network
Deploy 'CounterApp' to network [completed]
Generate deployment artifacts [started]
Generate deployment artifacts [completed]
Deploy contract [completed]
Determine contract address for version [started]
Determine contract address for version [completed]
Check for --http-served-from argument and copy manifest.json to destination [started]
Check for --http-served-from argument and copy manifest.json to destination [completed]
Generate application artifact [started]
Generate application artifact [skipped]
→ Using existent artifact
Publish foo.aragonpm.eth [started]
→ Generating transaction and waiting for confirmation
Publish foo.aragonpm.eth [completed]
Fetch published repo [started]
Fetch published repo [completed]
Publish app to APM [completed]
Create DAO [started]
Fetching kit bare-kit.aragonpm.eth@latest [started]
Fetching kit bare-kit.aragonpm.eth@latest [completed]
Create new DAO from kit [started]
Create new DAO from kit [completed]
Checking DAO [started]
Checking DAO [completed]
Create DAO [completed]
Open DAO [started]
Download client [started]
Download client [skipped]
→ Client already downloaded
Start Aragon client [started]
Start Aragon client [completed]
Open client [started]
Open client [completed]
Open DAO [completed]
```

Where do we add the app to the dao?
Also does it makes sense to output the counter app contract address?

**Comment by galactusss** [comment] 2018-12-04 23:10
I tested with all the kits and is working fine. I had to follow the steps in this order:
1. `aragon init foo`
2. `npm run start:app`
3. `npm run start:aragon:http`

Got this behavior only if I stop the server running the app. 

@0x6431346e  I tested on Mac. Do you think is safe to close this issue? Or I should test it with a virtual machine on linux and windows?

**Comment by sohkai** [comment] 2018-12-06 17:13
Ahh, it could be that you weren't running `start:app` first, as [documented](https://github.com/aragon/aragon-react-kit-boilerplate/blob/master/README.md#using-http).

This server needs to be available for it to fetch the metadata (artifact.json, manifest.json) in order for aragon/aragon and the CLI to display it as an app.

**Comment by galactusss** [comment] 2018-12-10 21:56
I'm reopening this issue. I experienced the behavior again. But I found the root of the problem. I explain it next: 

When running for the first time `npm run start:aragon:http` the command fail with this message
<img width="800" alt="image" src="https://user-images.githubusercontent.com/9082013/49763546-b91b9580-fcab-11e8-9bd1-9055650bfef0.png">

This command generate file artifact.json on ./dist directory anyways, but the file is corrupted.
<img width="1613" alt="image" src="https://user-images.githubusercontent.com/9082013/49763775-5b3b7d80-fcac-11e8-8c23-b74cc74de0ab.png">
<img width="1558" alt="image" src="https://user-images.githubusercontent.com/9082013/49763795-68586c80-fcac-11e8-8fde-72a24a8ff2a8.png">
On the left the corrupted and on the right a working example.

I fixed the problem deleting corrupted artifact.json and running previous command with global aragonCLI (version 5.2.1)

I'm not sure why the problem is also related with aragonCLI version, might be related to https://github.com/trufflesuite/ganache-core/pull/239 ? @0x6431346e @sohkai

**Comment by galactusss** [comment] 2018-12-10 22:04
I forgot to add that if we didn't delete artifact.json. The task of `aragon run --http` corresponding to generate artifact.json is skipped if a file exist. So it isn't updated once corrupted

**Comment by sohkai** [comment] 2018-12-11 14:08
Super weird... maybe we're not writing the file correctly, or it's something to do with how the `arapp.json`'s `environment` field is added to the boilerplates (I know @perissology added some migration code to the format).

**Comment by galactusss** [comment] 2018-12-20 22:58
Will be solve when this PR merge https://github.com/aragon/aragon-react-kit-boilerplate/pull/21

**Closed** 2018-12-20 23:11 UTC
Labels: bug, priority: high
