### ISSUE TITLE
Insufficient funds for gas * price + value

### ISSUE THREAD

**Issue by luisivan** [aragon/aragon-cli#466] opened 2019-05-15 13:39 UTC
## 🐛 Bug Report

(A clear and concise description of what the bug is)

```
     → Returned error: {"id":6,"jsonrpc":"2.0","error":"insufficient funds for gas …
 ✖ Returned error: {"id":6,"jsonrpc":"2.0","error":"insufficient funds for gas * price + value"}
```

#### Mainnet or testnet?

Mainnet

#### Organization

holdings.aragonid.eth

#### Environment

- OS and OS version: Latest Manjaro Linux
- Browser and browser version: Brave 0.63.55
- Add any other context about the problem here: Using Frame

## To Reproduce

Execute this command: `dao install 0xd0e6765f2b08b8C93F3d8E07B790A13b1208e905 token-manager --app-init none --use-frame --environment aragon:mainnet`

Tried with both setting Frame to use Infura, as well as Aragon's node.

## Expected behavior

To install a new instance of the Token Manager.

## Actual Behavior

Crashes with gas error. Also happens to other commands such as `dao act`, but it didn't happen with `dao token new`.

**Comment by 0xGabi** [comment] 2019-05-27 06:34
@luisivan the issue were cause by ganache (related to https://github.com/aragon/aragen/pull/45 and https://github.com/trufflesuite/ganache-core/issues/417). 

I tested on devchain and rinkeby and it worked for me. I also checked the same command you shared and I got a transaction path error, most likely cause I don't have permissions. So, it should work now 👍

I suggest you to add the option `--apm.ipfs.rpc https://ipfs.eth.aragon.network/ipfs` to fetch the artifacts.json from the Aragon IPFS gateway.

Let me know if it worked!

**Comment by luisivan** [comment] 2019-05-27 08:15
I'm still getting the exact same issue, even with version 5.9.3 :/

But it seems like I'm getting it also with other kind of transactions, so at this point unsure if this is a Frame issue.

BTW this is an unrelated issue, but the only way I can go around the IPFS problems is by running `aragon ipgs`. The `apm.ipfs.rpc` flag doesn't do the trick for me.

**Comment by 0xGabi** [comment] 2019-05-29 21:25
@luisivan I was not able to reproduce the issue. I only got the same error message if I choose an account without funds on Frame.

To isolate the problem from Frame, can you test with a hot wallet and make a similar transaction? To configure a private key on the `aragonCLI` you can [follow this section of the documentation](https://hack.aragon.org/docs/guides-faq#set-a-private-key). Thanks

**Comment by 0xGabi** [comment] 2019-06-24 14:33
Hey @luisivan do you still having this issue?

Nevertheless we think to improve error message here to display account address and amount.

**Comment by 0xGabi** [comment] 2019-08-01 17:54
Now that the new stable version is out I think we can close this one. Feel free to reopen if problem happened again

**Closed by 0xGabi** 2019-08-01 17:54 UTC
Labels: cmd: dao act, cmd: dao install, 🐛 bug
