### ISSUE TITLE
"dao apps" command is unable to fetch data from IPFS

### ISSUE THREAD

**Issue by xuhcc** [aragon/aragon-cli#881] opened 2019-11-07 21:06 UTC
## 🐛 Bug Report

`dao apps` command is unable to fetch data from IPFS:

```
Fetching repo content failed Error: Provider not supported: ipfs
```

### Have you read the [Contributing Guidelines on issues](https://github.com/aragon/aragon-cli/blob/master/CONTRIBUTING.md#ways-to-contribute)?

Yes.

#### Mainnet or testnet?

Mainnet.

#### Organization

Any organization. For example, Livepeer org: https://mainnet.aragon.org/#/0x0ee165029b09d91a54687041adbc705f6376c67f

#### Environment

- OS and OS version: Arch Linux
- Browser and browser version: N/A
- Aragon CLI: 6.3.3

## To Reproduce

1. Run `aragon ipfs`.
2. Run `dao apps 0x0ee165029b09d91a54687041adbc705f6376c67f --all  --environment aragon:mainnet` in another terminal.

## Expected behavior

I expect that command would run without errors as described in https://hack.aragon.org/docs/guides-use-agent#4-set-permissions

## Actual Behavior

Several errors are printed to console:

```
Fetching repo content failed Error: Provider not supported: ipfs
    at fetchRepoContentURI (/usr/lib/node_modules/@aragon/cli/node_modules/@aragon/wrapper/src/core/apm/repo.js:62:11)
    at fetchRepoContentFromVersion (/usr/lib/node_modules/@aragon/cli/node_modules/@aragon/wrapper/src/core/apm/index.js:21:24)
    at Object.fetchRepoContentFromVersion [as fetchLatestRepoContentForContract] (/usr/lib/node_modules/@aragon/cli/node_modules/@aragon/wrapper/src/core/apm/index.js:49:14)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

The report says "No UI available" for all entries:

```
✔ Successfully fetched DAO apps for 0x0ee165029b09d91a54687041adbc705f6376c67f
┌────────────────────────────────────────────────────────────────────┬────────────────────────────────────────────┬───────────────────┐
│ App                                                                │ Proxy address                              │ Content           │
├────────────────────────────────────────────────────────────────────┼────────────────────────────────────────────┼───────────────────┤
│ kernel                                                             │ 0x0ee165029b09d91a54687041adbc705f6376c67f │ (No UI available) │
├────────────────────────────────────────────────────────────────────┼────────────────────────────────────────────┼───────────────────┤
│ acl                                                                │ 0x439ceb885fffbb29c52125134d6c8c79eb462293 │ (No UI available) │
├────────────────────────────────────────────────────────────────────┼────────────────────────────────────────────┼───────────────────┤
│ evmreg                                                             │ 0xcd3f0210f999c7521bf21a97a96cc1a77cfe7203 │ (No UI available) │
├────────────────────────────────────────────────────────────────────┼────────────────────────────────────────────┼───────────────────┤
│ voting                                                             │ 0xe2445e061e016f5f283c3b85c0619dc45153685b │ (No UI available) │
├────────────────────────────────────────────────────────────────────┼────────────────────────────────────────────┼───────────────────┤
│ vault                                                              │ 0xee1ee71ed533f62bc870edff9cd25f42ded861c9 │ (No UI available) │
├────────────────────────────────────────────────────────────────────┼────────────────────────────────────────────┼───────────────────┤
│ finance                                                            │ 0x296ce9f234cd756861f30ff32bfd2198b890e44b │ (No UI available) │
├────────────────────────────────────────────────────────────────────┼────────────────────────────────────────────┼───────────────────┤
│ token-manager                                                      │ 0x40314c178008e5e59401c7f69d146836a40bdfcb │ (No UI available) │
├────────────────────────────────────────────────────────────────────┼────────────────────────────────────────────┼───────────────────┤
│ 0x668fe7ef9366b1f27e1e18a59fd2cdec041ad223e3506bf0cb6d1ab981781e75 │ 0x7b3e5207acdc4f322c1f471c97810ba29a4f8500 │ (No UI available) │
└────────────────────────────────────────────────────────────────────┴────────────────────────────────────────────┴───────────────────┘
```

**Comment by macor161** [comment] 2019-11-08 20:43
Hi @xuhcc, thanks for submitting this issue. After a few test, I can confirm that this bug is currently fixed on our `master` branch. It was caused by a missing ipfs config param here: https://github.com/aragon/aragon-cli/blob/v6.3.3/packages/aragon-cli/src/commands/dao_cmds/apps.js#L63

@0xGabi What do you think if we publish a release in the coming days for what we have on master. I think there are some helpful fixes for app names as well.

**Comment by xuhcc** [comment] 2019-11-15 00:28
I can confirm that errors are gone in aragon-cli 6.4.0.

**Closed** 2019-11-15 16:18 UTC
Labels: cmd: dao apps, 🐛 bug
