### ISSUE TITLE
Fails to install on macOS Mojave

### ISSUE THREAD

**Issue by luisivan** [aragon/aragon-cli#494] opened 2019-06-01 08:45 UTC
## 🐛 Bug Report

Fails to install on macOS Mojave.

## To Reproduce

`npm i -g @aragon/cli`

## Expected behavior

Should install fine.

## Actual Behavior

Doesn't install. I think this is because of some native bindings failing to compile.
```
make: *** [Release/obj.target/sha3/src/addon.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:200:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 18.5.0
gyp ERR! command "/usr/local/Cellar/node/12.3.1/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/@aragon/cli/node_modules/ganache-core/node_modules/sha3
gyp ERR! node -v v12.3.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: scrypt@6.0.3 (node_modules/@aragon/cli/node_modules/ganache-core/node_modules/scrypt):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: scrypt@6.0.3 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sha3@1.2.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sha3@1.2.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by 0x6431346e** [comment] 2019-06-04 13:34
Duplicate of #461 

It seems that there's already a commit in `ganache-core` that will fix it.

**Closed by 0x6431346e** 2019-06-04 13:34 UTC
Labels: 🐛 bug
