### ISSUE TITLE
aragon dao foo ... doesn't error

### ISSUE THREAD

**Issue by sohkai** [aragon/aragon-cli#372] opened 2019-02-21 16:23 UTC
`aragon dao <non-recognized command` seems to just hang.

E.g.

```
aragon dao foo 0x97a7dd9ac599f621759269cedab91c66ca6e44ef 0xec67005c4e498ec7f55e092bd1d35cbc4
7c91892 'transfer(address,uint256)' 0x0d580ae50B58fe08514dEAB4e38c0DFdB0D30adC 1 --environment aragon:mainnet
```

**Comment by dapplion** [comment] 2019-10-27 22:51
I am not able to reproduce the behavior you reported.
> aragon dao <non-recognized command seems to just hang.

In my environment the command errors quickly
```
lion@lion-gram:~/$ uname -a
Linux lion-gram 4.15.0-20-generic #21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

Raw command
```
lion@lion-gram:~/$ aragon dao foo
✖ You need to specify a command
 dao <command>
... (regular --help print)
```
With arguments
```
lion@lion-gram:~/$ aragon dao foo 0x97a7dd9ac599f621759269cedab91c66ca6e44ef 0xec67005c4e498ec7f55e092bd1d35cbc47c91892 'transfer(address,uint256)' 0x0d580ae50B58fe08514dEAB4e38c0DFdB0D30adC 1 --environment aragon:mainnet
✖ Unknown arguments: 0x97a7dd9ac599f621759269cedab91c66ca6e44ef, 0xec67005c4e498ec7f55e092bd1d35cbc47c91892, transfer(address,uint256), 0x0d580ae50B58fe08514dEAB4e38c0DFdB0D30adC, 1
 dao <command>
... (regular --help print)
```

**Comment by 0xGabi** [comment] 2019-10-28 13:54
I checked with my system (MacOS) and is no longer an issue. We can close the issue and if someone have the problem again feel free to re-open it

**Closed by 0xGabi** 2019-10-28 13:54 UTC
Labels: :pray: good first issue, 🐛 bug

**Comment by dapplion** [comment] 2019-10-30 22:50
Awesome
