### ISSUE TITLE
npm ERR! peer dep missing

### ISSUE THREAD

**Issue by xmaysonnave** [aragon/aragon-cli#700] opened 2019-08-08 07:04 UTC
Environment :

- Debian buster, Linux 4.19.0-5-amd64 
- node, `v10.16.2`
- npm, `6.10.3`
- made a clean install, `npm -g install @aragon/cli`

Here is the result of `npm -g ls --depth=0` :

/home/xavier/.npm-global/lib
├── @aragon/cli@6.2.3
└── npm@6.10.3

npm ERR! peer dep missing: acorn@^6.0.0, required by acorn-jsx@5.0.1
npm ERR! peer dep missing: acorn@^6.0.0, required by acorn-jsx@5.0.1
npm ERR! missing: @aragon/cli-utils@^0.0.6, required by @aragon/aragen@5.0.7

Thanks

**Comment by sohkai** [comment] 2019-10-15 10:20
This is quite awkward, AFAIK it's installing fine elsewhere. cc @macor161 could you try to reproduce on a clean virtual machine?

**Comment by xmaysonnave** [comment] 2019-10-15 10:35
Hi All,

Just made a new test as I recently upgrade my environment :
- Debian buster, Kernel 5.2.0-0.bpo.3-amd64 
- node, `v11.15.0`
- npm, `6.12.0`
- made a clean install, `npm -g install @aragon/cli`

Here is the result of `npm -g ls --depth=0` :

/home/xavier/.npm-global/lib
├── @aragon/cli@6.3.3
└── npm@6.12.0

npm ERR! peer dep missing: acorn@^6.0.0 || ^7.0.0, required by acorn-jsx@5.0.2
npm ERR! peer dep missing: acorn@^6.0.0 || ^7.0.0, required by acorn-jsx@5.0.2
npm ERR! missing: websocket@github:web3-js/WebSocket-Node#polyfill/globalThis, required by web3-providers-ws@1.2.1

One ERR disappeared -> @aragon/cli-utils@^0.0.6
The ERR about websocket is new.

PS: What is your node version requirement as I can do further tests ?

Thanks

**Comment by macor161** [comment] 2019-10-15 13:13
Hi @xmaysonnave can you post your install logs?
I did a quick test on a Debian vm and it seems to be working fine here.
Regarding the node version requirements, `>=8` should work. I would recommend not to use `12` at the moment.

**Comment by xmaysonnave** [comment] 2019-10-16 04:54
Dear Friends,

Here are the requested report :
Again clean install, purge my global .npm and .npm-global then :
Update npm -> npm install -g npm
Install @aragon/cli -> npm -g install @aragon/cli --loglevel verbose --timing > log.txt 2>&1
Run: npm -g ls --depth=0
/home/xavier/.npm-global/lib
├── @aragon/cli@6.3.3
└── npm@6.12.0

npm ERR! peer dep missing: acorn@^6.0.0 || ^7.0.0, required by acorn-jsx@5.0.2
npm ERR! peer dep missing: acorn@^6.0.0 || ^7.0.0, required by acorn-jsx@5.0.2
npm ERR! missing: websocket@github:web3-js/WebSocket-Node#polyfill/globalThis, required by web3-providers-ws@1.2.1

Attached Files -> log.txt.tar.gz and _logs.tar.gz

Warmly

[_logs.tar.gz](https://github.com/aragon/aragon-cli/files/3732489/_logs.tar.gz)

[log.txt.tar.gz](https://github.com/aragon/aragon-cli/files/3732485/log.txt.tar.gz)

**Comment by macor161** [comment] 2019-10-18 00:33
Hi @xmaysonnave, so it's not related to husky as I have the same error on my VM and the CLI still gets installed correctly. How did you install nodejs? With `apt-get` or with `nvm`?

**Comment by xmaysonnave** [comment] 2019-10-18 04:46
Hi Matthew,

I'm going to make several posts to clarify each testing steps.
I cleanup my full env, removing also my home npm global directory.

1 - First test with default debian repo and no home npm global directory
sudo apt install nodejs
node -v
v10.15.2

sudo apt install npm
npm -v
5.8.0

As reported here: https://github.com/nodejs/help/issues/1877
Default Debian install is broken, my output is consistent

xavier@andaman  ~  npm -g ls --depth=0
npm WARN npm npm does not support Node.js v10.15.2
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/
/usr/local/lib
└── (empty)

The suggested solution is to update npm without sudo :
npm install npm@latest -g

As expected it crashed :

xavier@andaman  ~  npm install npm@latest -g
npm WARN npm npm does not support Node.js v10.15.2
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/
npm WARN checkPermissions Missing write access to /usr/local/lib
npm ERR! path /usr/local/lib
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access
npm ERR! Error: EACCES: permission denied, access '/usr/local/lib'
npm ERR!  { [Error: EACCES: permission denied, access '/usr/local/lib']
npm ERR!   stack:
npm ERR!    'Error: EACCES: permission denied, access \'/usr/local/lib\'',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib' }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/xavier/.npm/_logs/2019-10-18T04_36_20_140Z-debug.log

Try again with :
sudo npm install npm@latest -g

sudo npm install npm@latest -g
npm WARN npm npm does not support Node.js v10.15.2
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/
/usr/local/bin/npx -> /usr/local/lib/node_modules/npm/bin/npx-cli.js
/usr/local/bin/npm -> /usr/local/lib/node_modules/npm/bin/npm-cli.js
+ npm@6.12.0
added 430 packages from 839 contributors in 5.002s

xavier@andaman: npm -g ls --depth=0      
/usr/local/lib
└── npm@6.12.0

Looks good.

Try to install @aragon/cli globally without sudo. It doesn't work as expected.

xavier@andaman: npm -g install @aragon/cli
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules
npm ERR! code EACCES
npm ERR! syscall access
npm ERR! path /usr/local/lib/node_modules
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, access '/usr/local/lib/node_modules'
npm ERR!  { [Error: EACCES: permission denied, access '/usr/local/lib/node_modules']
npm ERR!   stack:
npm ERR!    'Error: EACCES: permission denied, access \'/usr/local/lib/node_modules\'',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib/node_modules' }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

Try to install @aragon/cli globally with sudo: 
sudo npm -g install @aragon/cli

Doesn't work either, here is an excerpt of my output:

> keccak@1.4.0 install /usr/local/lib/node_modules/@aragon/cli/node_modules/ganache-core/node_modules/keccak
> npm run rebuild || echo "Keccak bindings compilation fail. Pure JS implementation will be used."

npm ERR! code EACCES
npm ERR! syscall scandir
npm ERR! path /root/.npm/_logs
npm ERR! errno -13
npm ERR! 
npm ERR! Your cache folder contains root-owned files, due to a bug in
npm ERR! previous versions of npm which has since been addressed.
npm ERR! 
npm ERR! To permanently fix this problem, please run:
npm ERR!   sudo chown -R 65534:1000 "/root/.npm"
glob error { [Error: EACCES: permission denied, scandir '/root/.npm/_logs']
  errno: -13,
  code: 'EACCES',
  syscall: 'scandir',
  path: '/root/.npm/_logs' }

Another bunch of tests are coming in the next post (I need to cleanup my space).

Xavier

Thanks.

**Comment by xmaysonnave** [comment] 2019-10-18 05:18
2 - Second round of tests
Install as before nodejs and npm from default Debian repo.

Define a npm global directory in my home folder:

# directory where npm will install packages
mkdir ~/.npm-global
# configure npm
npm config set prefix '~/.npm-global'
# following the previous command ~/.npmrc should contain:
prefix=/home/xavier/.npm-global
# update .profile or .zshrc with
export PATH=~/.npm-global/bin:$PATH
# update your system variables
source ~/.profile or source ~/.zshrc

Update npm to the latest in this configuration.
xavier@andaman: which npm
/home/xavier/.npm-global/bin/npm

Looks good:
xavier@andaman: npm -g ls --depth=0         
/home/xavier/.npm-global/lib
└── npm@6.12.0

Then install @aragon/cli: npm install -g @aragon/cli

As you have noticed, husky is complaining :
Command failed: git rev-parse --show-toplevel --absolute-git-dir
fatal: not a git repository (or any of the parent directories): .git
husky > Failed to install

xavier@andaman npm -g ls --depth=0       
/home/xavier/.npm-global/lib
├── @aragon/cli@6.3.3
└── npm@6.12.0

npm ERR! peer dep missing: acorn@^6.0.0 || ^7.0.0, required by acorn-jsx@5.0.2
npm ERR! peer dep missing: acorn@^6.0.0 || ^7.0.0, required by acorn-jsx@5.0.2
npm ERR! missing: websocket@github:web3-js/WebSocket-Node#polyfill/globalThis, required by web3-providers-ws@1.2.1

Same error as already reported.

Xavier

Thanks

**Comment by xmaysonnave** [comment] 2019-10-18 05:40
3 - Third round of tests:
Use nodesource repo instead of debian repo, using node 11.x instead of 10.x

/etc/apt/source.list.d/nodesource.list
deb https://deb.nodesource.com/node_11.x buster main
deb-src https://deb.nodesource.com/node_11.x buster main

sudo apt update
sudo apt install nodejs

node -v
v11.15.0

npm -v
6.7.0

sudo npm -g ls --depth=0
/usr/lib
└── npm@6.7.0

Upgrade npm globally
sudo npm install -g npm@latest
/usr/bin/npm -> /usr/lib/node_modules/npm/bin/npm-cli.js
/usr/bin/npx -> /usr/lib/node_modules/npm/bin/npx-cli.js
+ npm@6.12.0
added 22 packages from 15 contributors, removed 18 packages and updated 59 packages in 4.195s

npm -v
6.12.0

sudo npm -g ls --depth=0      
/usr/lib
└── npm@6.12.0

Looks good

Try to install @aragon/cli globally: sudo npm -g install @aragon/cli
It crashed again.

Xavier
Thanks

**Comment by xmaysonnave** [comment] 2019-10-18 06:28
4 - Third round of tests:
Install nodejs from nodesource repo:

node -v
v11.15.0
6.7.0

which npm
/usr/bin/npm

which node
/usr/bin/node

Looks good as expected.

Define a npm global directory in my home folder:
PATH=/snap/bin:/home/xavier/go:/home/xavier/go/bin:/home/xavier/.npm-global/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games

npm install -g npm@latest
/home/xavier/.npm-global/bin/npx -> /home/xavier/.npm-global/lib/node_modules/npm/bin/npx-cli.js
/home/xavier/.npm-global/bin/npm -> /home/xavier/.npm-global/lib/node_modules/npm/bin/npm-cli.js
+ npm@6.12.0
added 430 packages from 839 contributors in 8.707s

Something wrong here while the PATH has been properly setup beforehand.
which npm
/usr/bin/npm

Closed my current terminal and open a new one.
which npm
/home/xavier/.npm-global/bin/npm

npm -v
6.12.0

as expected

install @aragon/cli globally on my home folder.
npm install -g @aragon/cli

Build proces is ok:
+ @aragon/cli@6.3.3
added 3603 packages from 2397 contributors in 237.286s

Same error as before.

npm -g ls --depth=0       
/home/xavier/.npm-global/lib
├── @aragon/cli@6.3.3
└── npm@6.12.0

npm ERR! peer dep missing: acorn@^6.0.0 || ^7.0.0, required by acorn-jsx@5.0.2
npm ERR! peer dep missing: acorn@^6.0.0 || ^7.0.0, required by acorn-jsx@5.0.2
npm ERR! missing: websocket@github:web3-js/WebSocket-Node#polyfill/globalThis, required by web3-providers-ws@1.2.1

I'm going to use test nvm. Not familiar with it though.

Xavier
Thanks

**Comment by xmaysonnave** [comment] 2019-10-18 07:00
5 - use nvm
nvm setup with .zshrc
especially :
https://github.com/nvm-sh/nvm#calling-nvm-use-automatically-in-a-directory-with-a-nvmrc-file

The husky error vanished, good. However errors remain:

npm -g ls --depth=0       
/home/xavier/.nvm/versions/node/v11.15.0/lib
├── @aragon/cli@6.3.3
└── npm@6.12.0

npm ERR! peer dep missing: acorn@^6.0.0 || ^7.0.0, required by acorn-jsx@5.0.2
npm ERR! peer dep missing: acorn@^6.0.0 || ^7.0.0, required by acorn-jsx@5.0.2
npm ERR! missing: websocket@github:web3-js/WebSocket-Node#polyfill/globalThis, required by web3-providers-ws@1.2.1

Xavier
Thanks

**Comment by xmaysonnave** [comment] 2019-10-19 08:40
6 - use nvm and build from source
git clone https://github.com/aragon/aragon-cli.git
cd aragon-cli
git checkout tags/v6.3.3
cd packages
cd aragon-cli
npm install

npm ls --depth=0 
@aragon/cli@6.3.3 /work/solidity/aragon-cli/packages/aragon-cli
├── @aragon/apm@3.1.0
├── @aragon/apps-agent@1.1.1
├── @aragon/apps-finance@3.0.0
├── @aragon/apps-payroll@1.0.0
├── @aragon/apps-shared-minime@1.0.2
├── @aragon/apps-survey@1.0.0
├── @aragon/apps-token-manager@2.1.0
├── @aragon/apps-vault@4.1.0
├── @aragon/apps-voting@2.1.0
├── @aragon/aragen@5.3.5
├── @aragon/cli-utils@0.0.8
├── @aragon/id@2.1.0
├── @aragon/os@4.3.0
├── @aragon/wrapper@5.0.0-rc.17
├── @babel/cli@7.6.2
├── @babel/core@7.6.2
├── @babel/node@7.6.2
├── @babel/plugin-proposal-object-rest-spread@7.6.2
├── @babel/preset-env@7.6.2
├── @babel/register@7.6.2
├── ajv@6.10.2
├── ava@2.4.0
├── babel-eslint@10.0.3
├── byte-size@5.0.1
├── chalk@2.4.2
├── cli-table@0.3.1
├── core-js@3.2.1
├── del-cli@2.0.0
├── dev-null@0.1.1
├── documentation@12.1.2
├── eslint@6.4.0
├── eslint-config-prettier@6.3.0
├── eslint-config-standard@12.0.0
├── eslint-plugin-ava@7.1.0
├── eslint-plugin-import@2.18.2
├── eslint-plugin-node@9.2.0
├── eslint-plugin-prettier@3.1.1
├── eslint-plugin-promise@4.2.1
├── eslint-plugin-standard@4.0.1
├── eth-ens-namehash@2.0.8
├── ethereum-ens@0.7.8
├── execa@1.0.0
├── find-up@4.1.0
├── fs-extra@8.1.0
├── get-folder-size@2.0.1
├── git-clone@0.1.0
├── go-platform@1.0.0
├── http-server@0.11.1
├── husky@3.0.7
├── ignore@4.0.6
├── inquirer@6.5.2
├── internal-ip@4.3.0
├── ipfs-api@26.1.2
├── ipfs-http-client@33.1.1
├── js-sha3@0.8.0
├── lint-staged@9.4.0
├── listr@0.14.3
├── listr-input@0.1.3
├── lodash.merge@4.6.2
├── node-fetch@2.6.0
├── nyc@14.1.1
├── open@6.4.0
├── prettier@1.18.2
├── proxyquire@2.1.3
├── public-ip@3.2.0
├── regenerator-runtime@0.13.3
├── replace@1.1.1
├── semver@6.3.0
├── sinon@7.5.0
├── source-map-support@0.5.13
├── stringify-tree@1.0.2
├── tmp-promise@2.0.2
├── truffle@4.1.14
├── truffle-flattener@1.4.2
├── truffle-hdwallet-provider@1.0.17
├── truffle-hdwallet-provider-privkey@0.3.0
├── web3@1.2.1
├── web3-eth-abi@1.2.1
├── web3-utils@1.2.1
├── which@1.3.1
└── yargs@13.3.0

npm ERR! extraneous: @types/web3@1.0.19 /work/solidity/aragon-cli/packages/aragon-cli/node_modules/ganache-core/node_modules/@types/web3
npm ERR! extraneous: assert-match@1.1.1 /work/solidity/aragon-cli/packages/aragon-cli/node_modules/ganache-core/node_modules/assert-match
npm ERR! extraneous: browserfs@1.4.3 /work/solidity/aragon-cli/packages/aragon-cli/node_modules/ganache-core/node_modules/browserfs
npm ERR! extraneous: coveralls@3.0.6 /work/solidity/aragon-cli/packages/aragon-cli/node_modules/ganache-core/node_modules/coveralls
npm ERR! extraneous: cross-env@5.2.0 /work/solidity/aragon-cli/packages/aragon-cli/node_modules/ganache-core/node_modules/cross-env
npm ERR! extraneous: eslint@5.7.0 /work/solidity/aragon-cli/packages/aragon-cli/node_modules/ganache-core/node_modules/eslint
npm ERR! extraneous: eslint-config-standard@12.0.0 /work/solidity/aragon-cli/packages/aragon-cli/node_modules/ganache-core/node_modules/eslint-config-standard
npm ERR! extraneous: eslint-plugin-import@2.14.0 /work/solidity/aragon-cli/packages/aragon-cli/node_modules/ganache-core/node_modules/eslint-plugin-import
npm ERR! extraneous: eslint-plugin-node@7.0.1 /work/solidity/aragon-cli/packages/aragon-cli/node_modules/ganache-core/node_modules/eslint-plugin-node
npm ERR! extraneous: eslint-plugin-promise@4.2.1 /work/solidity/aragon-cli/packages/aragon-cli/node_modules/ganache-core/node_modules/eslint-plugin-promise
npm ERR! extraneous: eslint-plugin-standard@4.0.0 /work/solidity/aragon-cli/packages/aragon-cli/node_modules/ganache-core/node_modules/eslint-plugin-standard
npm ERR! extraneous: ethers@4.0.26 /work/solidity/aragon-cli/packages/aragon-cli/node_modules/ganache-core/node_modules/ethers
npm ERR! extraneous: husky@1.3.1 /work/solidity/aragon-cli/packages/aragon-cli/node_modules/ganache-core/node_modules/husky
npm ERR! extraneous: js-scrypt@0.2.0 /work/solidity/aragon-cli/packages/aragon-cli/node_modules/ganache-core/node_modules/js-scrypt
npm ERR! extraneous: lint-staged@8.2.1 /work/solidity/aragon-cli/packages/aragon-cli/node_modules/ganache-core/node_modules/lint-staged
npm ERR! extraneous: mocha@5.2.0 /work/solidity/aragon-cli/packages/aragon-cli/node_modules/ganache-core/node_modules/mocha
npm ERR! extraneous: mocha-lcov-reporter@1.3.0 /work/solidity/aragon-cli/packages/aragon-cli/node_modules/ganache-core/node_modules/mocha-lcov-reporter
npm ERR! extraneous: nyc@14.1.1 /work/solidity/aragon-cli/packages/aragon-cli/node_modules/ganache-core/node_modules/nyc
npm ERR! extraneous: pify@4.0.0 /work/solidity/aragon-cli/packages/aragon-cli/node_modules/ganache-core/node_modules/pify
npm ERR! extraneous: portfinder@1.0.21 /work/solidity/aragon-cli/packages/aragon-cli/node_modules/ganache-core/node_modules/portfinder
npm ERR! extraneous: prettier@1.18.2 /work/solidity/aragon-cli/packages/aragon-cli/node_modules/ganache-core/node_modules/prettier
npm ERR! extraneous: solc@0.5.10 /work/solidity/aragon-cli/packages/aragon-cli/node_modules/ganache-core/node_modules/solc
npm ERR! extraneous: temp@0.8.3 /work/solidity/aragon-cli/packages/aragon-cli/node_modules/ganache-core/node_modules/temp
npm ERR! extraneous: terser-webpack-plugin@1.3.0 /work/solidity/aragon-cli/packages/aragon-cli/node_modules/ganache-core/node_modules/terser-webpack-plugin
npm ERR! extraneous: webpack@4.17.1 /work/solidity/aragon-cli/packages/aragon-cli/node_modules/ganache-core/node_modules/webpack
npm ERR! extraneous: webpack-bundle-size-analyzer@2.7.0 /work/solidity/aragon-cli/packages/aragon-cli/node_modules/ganache-core/node_modules/webpack-bundle-size-analyzer
npm ERR! extraneous: webpack-cli@3.1.0 /work/solidity/aragon-cli/packages/aragon-cli/node_modules/ganache-core/node_modules/webpack-cli
npm ERR! peer dep missing: acorn@^6.0.0 || ^7.0.0, required by acorn-jsx@5.0.2
npm ERR! peer dep missing: acorn@^6.0.0 || ^7.0.0, required by acorn-jsx@5.0.2
npm ERR! missing: websocket@github:web3-js/WebSocket-Node#polyfill/globalThis, required by web3-providers-ws@1.2.1

Xavier
Thanks

**Comment by macor161** [comment] 2019-10-19 13:57
Hey @xmaysonnave, I'm sorry to see that you seem to have spent a significant amount of time on this. What do you think if we set up a call to fix your problem? I think it would be much more productive. And I'm confident we can make it work 🙂 I'm `mcormier` on keybase.

**Comment by xmaysonnave** [comment] 2019-10-21 03:41
Hi Matthew,
Don't be sorry. Every problems is an opportunity to learn and grow.
See you on Keybase.

As you have noticed in my reports, the husky problem vanished while using nvm.
It's probably worth to consider as npm is recommended to build @aragon/cli.

Warmly

**Comment by sohkai** [comment] 2020-04-18 17:53
Closing for now—this seems to have been an issue with the local node environment.

**Closed by sohkai** 2020-04-18 17:53 UTC
Labels: 🐛 bug

**Comment by macor161** [comment] 2020-04-20 02:29
Yes I can confirm that this is resolved.
