### ISSUE TITLE
Weird undefined error when deploying template

### ISSUE THREAD

**Issue by vporton** [aragon/aragon-cli#1196] opened 2020-01-11 02:14 UTC
## 🐛 Bug Report

`Deploy 'Template' to network` mysteriously fails with `Returned error: execution error: undefined`.

### Have you read the [Contributing Guidelines on issues](https://github.com/aragon/aragon-cli/blob/master/CONTRIBUTING.md#ways-to-contribute)?

Yes.

#### Mainnet or testnet?

RPC

#### Environment

- OS and OS version: Ubuntu 19.10
- Add any other context about the problem here.

## To Reproduce

(Write your steps here:)

1. Download https://github.com/vporton/courts/tree/weird-bug

1. `npm start`

## Actual Behavior

  ✔ Check port
  ✔ Start IPFS
  ✔ Start IPFS
  ✔ Start a local Ethereum network
  ✔ Setup before publish
  ✔ Prepare for publish
  ✔ Publish app to aragonPM
  ✔ Fetch published repo
  ❯ Deploy Template
    ✔ Compile contracts
    ✖ Deploy 'Template' to network
      → Returned error: execution error: undefined
      Generate deployment artifacts
    Create Organization
    Start Client
✖ Returned error: execution error: undefined

## Reproducible Demo

https://github.com/vporton/courts/tree/weird-bug

## Notes

Weirdly enough, it starts without an error if I comment out `trustCourts()` function. Is the problem with the contract code size? (But my contract isn't particularly big.)

**Comment by macor161** [comment] 2020-01-13 03:48
Closing this as it is a duplicate of #1190

**Closed by macor161** 2020-01-13 03:48 UTC
