### ISSUE TITLE
incorrect babel version for the ui

### ISSUE THREAD

**Issue by jvluso** [aragon/aragon-cli#217] opened 2018-10-01 21:54 UTC
![screenshot from 2018-10-01 14-48-58](https://user-images.githubusercontent.com/8061735/46317934-af7a0100-c589-11e8-888f-3b43b532f335.png)

The rest of the cli other than the browser ui is working.

**Comment by Quazia** [comment] 2018-10-01 22:46
I bumped into this locally and it ended up being related to babel-styled-component-plugins, I'm going to look into this tonight.

**Comment by Quazia** [comment] 2018-10-01 23:08
Wait, is this fixed by #216 ? @0x6431346e

**Comment by 0x6431346e** [comment] 2018-10-02 05:02
Yes, and by https://github.com/aragon/aragon-react-boilerplate/pull/27

This is duplicate of https://github.com/aragon/aragon-cli/issues/215 , which I suppose I shouldn't have closed :smile:

**Closed** 2018-10-25 18:41 UTC
Labels: bug
