### ISSUE TITLE
Can't not run localhost using `@aragon/cli version 7.1.1 `

### ISSUE THREAD

**Issue by blackinno** [aragon/aragon-cli#1540] opened 2020-03-05 04:57 UTC
## 🐛 Bug Report

```sh
> npm start

> mesg@1.0.0 start /Users/benthotsaphon/test-dir/aragon/aragon-application
> npm run start:ipfs

> mesg@1.0.0 start:ipfs /Users/benthotsaphon/test-dir/aragon/aragon-application
> aragon run --files dist

  ✔ Check port
  ↓ Start IPFS [skipped]
  ✔ Applying version bump (major)
  ✔ Building frontend
  ✔ Deploy contract
  ✔ Determine contract address for version
  ⠙ Prepare files for publishing
  ✔ Prepare files for publishing
  ✔ Generate application artifact
  ✖ Publish intent
    → undefined is not a valid semantic version
  ✔ Start IPFS
  ✔ Start a local Ethereum network
  ✔ Setup before publish
  ✖ Prepare for publish
    → undefined is not a valid semantic version
    Publish app to aragonPM
    Fetch published repo
    Fetching template bare-template.aragonpm.eth@latest
    Create Organization from template
    Start Client
✖ undefined is not a valid semantic version
```

### Have you read the [Contributing Guidelines on issues](https://github.com/aragon/aragon-cli/blob/master/CONTRIBUTING.md#ways-to-contribute)?

- [x] Yes

## To Reproduce

1. Clone https://github.com/mesg-foundation/aragon.git
2. Checkout to branch  `aragon-cli-update-version`
3. Go to `aragon-application` folder
4. Run `npm install`
5. Run `npm start`
6. See the error

## Expected behavior

Should run success on localhost

## Actual Behavior

```sh
> npm start

> mesg@1.0.0 start /Users/benthotsaphon/test-dir/aragon/aragon-application
> npm run start:ipfs

> mesg@1.0.0 start:ipfs /Users/benthotsaphon/test-dir/aragon/aragon-application
> aragon run --files dist

  ✔ Check port
  ↓ Start IPFS [skipped]
  ✔ Applying version bump (major)
  ✔ Building frontend
  ✔ Deploy contract
  ✔ Determine contract address for version
  ⠙ Prepare files for publishing
  ✔ Prepare files for publishing
  ✔ Generate application artifact
  ✖ Publish intent
    → undefined is not a valid semantic version
  ✔ Start IPFS
  ✔ Start a local Ethereum network
  ✔ Setup before publish
  ✖ Prepare for publish
    → undefined is not a valid semantic version
    Publish app to aragonPM
    Fetch published repo
    Fetching template bare-template.aragonpm.eth@latest
    Create Organization from template
    Start Client
✖ undefined is not a valid semantic version
```
<img width="1586" alt="Screen Shot 2563-03-05 at 11 44 57" src="https://user-images.githubusercontent.com/16553272/75948750-d3f0b000-5ed6-11ea-8cd3-93ae3e8edd0d.png">

#### Mainnet or testnet?

localhost

#### Environment

- OS and OS version: `macOS Catalina version 10.15.3`
- Aragon CLI version: `7.1.1`

## Reproducible Demo

```sh
> npm start

> mesg@1.0.0 start /Users/benthotsaphon/test-dir/aragon/aragon-application
> npm run start:ipfs

> mesg@1.0.0 start:ipfs /Users/benthotsaphon/test-dir/aragon/aragon-application
> aragon run --files dist

  ✔ Check port
  ↓ Start IPFS [skipped]
  ✔ Applying version bump (major)
  ✔ Building frontend
  ✔ Deploy contract
  ✔ Determine contract address for version
  ⠙ Prepare files for publishing
  ✔ Prepare files for publishing
  ✔ Generate application artifact
  ✖ Publish intent
    → undefined is not a valid semantic version
  ✔ Start IPFS
  ✔ Start a local Ethereum network
  ✔ Setup before publish
  ✖ Prepare for publish
    → undefined is not a valid semantic version
    Publish app to aragonPM
    Fetch published repo
    Fetching template bare-template.aragonpm.eth@latest
    Create Organization from template
    Start Client
✖ undefined is not a valid semantic version
```

**Comment by macor161** [comment] 2020-03-05 14:11
Hi @blackinno, thanks for reporting this. This should be fixed in `7.1.2`. In the meantime, you can use the stable version `7.0.3`.

- Fixed by #1510 
- Duplicate of #1124

**Closed** 2020-03-05 14:25 UTC
Labels: 🐛 bug
