### ISSUE TITLE
ENS name not defined?

### ISSUE THREAD

**Issue by Bloesum** [aragon/aragon-cli#177] opened 2018-08-20 16:12 UTC
Hi all,

I tried to create my own app with aragon-cli (4.1.5)  but when I 'aragon run' I keep getting the error 'ENS name not defined'. Am I missing something?

 ✔ Start a local Ethereum network
 ✔ Check IPFS
 ❯ Publish app to APM
   ✔ Deploy contract
   ↓ Automatically bump version [skipped]
     → Starting from initial version
   ✔ Determine contract address for version
   ✔ Building frontend
   ✔ Prepare files for publishing
   ✔ Generate application artifact
   ✔ Publish myApp2.aragonpm.eth
   ✖ Fetch published repo
     → ENS name not defined.
   Create DAO
   Open DAO
 ✖ ENS name not defined.

Regards,

Ewout

**Comment by sohkai** [comment] 2018-08-21 10:01
It might be something weird with the dev chain we set up.

Can you try `rm -rf ~/.aragon` and running it again?

**Comment by Bloesum** [comment] 2018-08-21 10:55
No, still same message 'ENS name not defined'.

**Comment by izqui** [comment] 2018-08-21 15:01
I can't reproduce either. Are you still getting the error if doing `aragon run --reset`?

**Comment by dentropy** [comment] 2018-11-16 21:18
You require more than just a ganache instance ganache requires an ENS deployment. The CLI tool uses aragen which you can run independently. https://github.com/aragon/aragen

**Comment by Quazia** [comment] 2018-11-30 14:18
If this can be replicated we can re-open. For now closing this issue.

**Closed** 2018-11-30 14:17 UTC
Labels: bug
